base_sistema/app/perfil/urls.py
from django.conf.urls import url
from .views import RegistroUsuario,index_perfils,empresas_index, \
Usuario_ListView,proveedores_list,Listado_empresas,Crear_empresa,Editar_empresa,Eliminar_empresa,PerfilCrear
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^index$', login_required(index_perfils), name='index'),
    url(r'^crear$', login_required(RegistroUsuario.as_view()), name='crear'),  # pasando los parametros de la url,index sera el
    # segundo patron que buscara django el primer patron a buscar es 'productos '
    # que es el que se encuentra dentro de el archivo de URLS  globales
    url(r'^usuario_list$', Usuario_ListView.as_view(), name='usuario_list'),
    url(r'^empresas_index$', empresas_index, name='empresas_index'),
    url(r'^empresa$', Crear_empresa.as_view(), name='empresa'),
    url(r'^empresas_list$', Listado_empresas.as_view(), name='empresas_list'),
    url(r'^editar/(?P<pk>\d+)/$',Editar_empresa.as_view(),name='empresas_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', Eliminar_empresa.as_view(), name='empresas_delete'),
    ##proveedores
    url(r'^proveedores_crear$', PerfilCrear.as_view(), name='proveedores_crear'),
    url(r'^proveedores_list$', proveedores_list, name='proveedores_list'),
   


]

base_sistema/app/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from app.productos.views import index_productos,Listado_producto,Editar_producto,Borrar_producto,\
Listado_pedido,Editar_pedido,Borrar_producto_pedido,Listado_categorias,inventario_view,Crear_producto,Detalles_producto,Crear_pedido

from django_filters.views import FilterView
from . filters import ProductoFilter
	
#la vista productos_view del archivo views.py

urlpatterns = [
    url(r'^index$', login_required(index_productos), name='index_productos'),#parametros de la url,index sera el
    #segundo patron que buscara django el primer patron a buscar es 'productos '
    #que es el que se encuentra dentro de el archivo de URLS  globales
   	url(r'^nuevo$', login_required(Crear_producto.as_view()), name='productos_nuevo'),
    url(r'^pedido$', login_required(Crear_pedido.as_view()), name='pedido_nuevo'),
   	url(r'^listar$', login_required(Listado_producto.as_view()), name='productos_listar'),
   	url(r'^editar/(?P<pk>\d+)/$', login_required(Editar_producto.as_view()), name='productos_editar'),
	url(r'^productos_detail/(?P<pk>\d+)/$', login_required(Detalles_producto.as_view()), name='productos_detail'),
   	url(r'^buscar_producto$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='producto_filtro_list.html')), name='buscar_producto'),
   	url(r'^eliminar/(?P<pk>\d+)/$', login_required(Borrar_producto.as_view()), name='productos_eliminar'),
   	url(r'^pedido_delete_producto/(?P<pk>\d+)/$', login_required(Borrar_producto_pedido.as_view()), name='pedido_delete_producto'),
   	url(r'^pedido_edit/(?P<pk>\d+)/$', login_required(Editar_pedido.as_view()) , name='pedido_edit'),#debe tener un id
   	#de producto hasta crear los botones en el template
	# url(r'^pedido_filtro$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='producto_id_filtro.html')), name='pedido_filtro'),
   	url(r'^pedido_list$', login_required(Listado_pedido.as_view()), name='pedido_list'),
    url(r'^categorias_list$', login_required(Listado_categorias.as_view()), name='categorias_list'),
    url(r'^inventario_view$', login_required(inventario_view), name='inventario_view'),
	url(r'^buscar_producto_por_empresa$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='stock_por_empresa_filtro_list.html')), name='buscar_producto_por_empresa'),

   	

]	

base_sistema/base_sistema/urls.py
# from django.conf.urls import url,include
# from django.contrib import admin
# from django.contrib.auth.views import login

# # from django.contrib.auth import views as auth_views
# # from django.views.generic.base import TemplateView


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from base_sistema.views import pedidoPDF,empresasPDF,perfilPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),#importando las urls del 
    #admin que trae django por defecto
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logout.html'}, name='logout'),
    url(r'^productos/', include('app.productos.urls', namespace="productos")),#name_space
    #son los nombres de las urls globalesy 'app.productos.urls' es la ruta del archivo  
    url(r'^perfil/', include('app.perfil.urls',namespace="perfil")),
    ## REPORTES GENERALES
    url(r'^pedido_pdf/',pedidoPDF.as_view(), name='pedido_pdf'),
    url(r'^empresas_pdf/',empresasPDF.as_view(), name='empresas_pdf'),
    url(r'^perfiles_pdf/',perfilPDF.as_view(), name='perfiles_pdf'),


]

base_sistema/app/perfil/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.db import models
from django.contrib.auth.models import Permission, User
#from app.productos.models import Categoria
# Create your models here.
#poner dos forek uno a productos y otro a categorias
class EmpresaProveedor(models.Model):#Este modelo aun o tiene un form para capturar los datos de la empresa
	nombre_empresa = models.CharField(max_length=50,default="")
	nit = models.CharField(max_length=20)#tipo de campo entero no recibe parametros
	telefono = models.CharField(max_length=50)
	contacto_email = models.EmailField()
	class Meta:
		verbose_name = "Empresa"
		verbose_name_plural = "Empresas"
	def __unicode__(self):#funcion para que se nos devuelva el nombre y no el objeto
	#que hemos registrado
		return '{}'.format(self.nombre_empresa)#en este caso la llave foranea del proveedor
		#y que nos muestre en un select el nombre de la empresa
	

	
#hacer llave foraea hacia la empresa para mostrar la empresa del proveedor

class Perfil(models.Model):
	
	empresa_proveedor = models.ForeignKey(EmpresaProveedor, null=True, blank= False,default="")
	usuario = models.OneToOneField(User)
	direccion = models.TextField(max_length=50, null=True)
	telefono = models.CharField( max_length=50)
	dui = models.CharField( max_length=50, null=True)
	nit = models.CharField( max_length=50, null=True)
	#no me permite importar categoria class
	#scategoria = models.ManyToManyField(Categoria, blank=True)
	class Meta:
		verbose_name = "Perfil"
		verbose_name_plural = "Perfiles"

	def __unicode__(self):#funcion para que se nos devuelva el nombre y no el objeto
	#que hemos registrado
		return '{}'.format(self.usuario)#en este caso la llave foranea del proveedor
		#y que nos muestre en un select el nombre de la empresa

base_sistema/app/perfil/forms.py
from django import forms
from .models import Perfil
from .models import EmpresaProveedor
from django.contrib.auth.models import Permission, User


class PerfilCrear(forms.ModelForm):
    class Meta:
        model = (Perfil)
        fields =('empresa_proveedor','usuario','direccion','telefono','dui','nit',)
	labels = {
	'usuario':			'Usuario',
	'empresa_proveedor': 'Empresa',
	'direccion':		'Direccion',
	'telefono':			'Telefono',
	'dui':				'DUI',
	'nit':				'NIT',

	}
	


class UsuarioCrear(forms.ModelForm):
    class Meta:
        model = (User)
        fields = ('username','first_name','last_name','password',)#campos traidos del modelo user

	# labels = {
	# 	'username':			'Usuario',
	# 	'first_name':		'Nombre',
	# 	'last_name':		'Apellido',
	# 	'password':			'Contrasena',
		
		

	# 	}

	# widgets	= {
	# #Creando los widgets
	# #El widget maneja la representacion del HTML 
	# #y la extraccion de datos de un diccionario GET / POST que corresponde al widget.
	# #dan la forma html

	# 	'username':forms.TextInput(attrs={'class':'form-control'}),#como atributo madamos 
	# 	#la clase from control de boostrap
	# 	'first_name':forms.TextInput(attrs={'class':'form-control'}),
	# 	'last_name':forms.TextInput(attrs={'class':'form-control'}),
	# 	'password':forms.TextInput(attrs={'class':'form-control'}),
		

				# }

class EmpresaCrear(forms.ModelForm):
	class Meta:
		model = (EmpresaProveedor)
		fields = ('nombre_empresa','nit','telefono','contacto_email')

	# labels = {
		
	# 	'nombre_empresa':	'nombre_empresa',
	# 	'nit':		        'nit',
	# 	'telefono':		    'telefono',
	# 	'contacto_email':	'contacto_email',
		
	# 	}


	# widgets	= {
		
		
	# 	'nombre_empresa':forms.TextInput(attrs={'class':'form-control'}),#como atributo madamos 
	# 	#la clase from control de boostrap
	# 	'nit':forms.TextInput(attrs={'class':'form-control'}),
	# 	'telefono':forms.TextInput(attrs={'class':'form-control'}),
	# 	'contacto_email':forms.TextInput(attrs={'class':'form-control'}),
		

	# 	}

base_sistema/app/perfil/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from .forms import PerfilCrear, UsuarioCrear,EmpresaCrear
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import EmpresaProveedor,Perfil



# Create your views here.



# Create your views here.
def index_perfils(request):
    return render(request,'index_perfil.html')

class RegistroUsuario(CreateView):
    model= User
    template_name = 'CRUD_usuarios.html'
    form_class = UserCreationForm
    success_url =reverse_lazy('perfil:usuario_list')
        
class Usuario_ListView(ListView):#recibe la peticion request
    #Creando Queryset con nombre producto
    #el modelo Producto y lo meto en la variable producto
    model = User
    template_name = 'lista_usuarios.html'




def empresas_index(request):
    return render(request,'empresas_index.html')

class PerfilCrear(CreateView):
    model= Perfil
    template_name = 'CRUD_Perfiles.html'
    form_class = PerfilCrear
    success_url =reverse_lazy('perfil:proveedores_list')

def proveedores_list(request):
    proveedor = Perfil.objects.all().order_by('id')
    contexto = {'proveedores':proveedor}
    return render(request, 'contactos_proveedores.html', contexto)

####### PASADO TODAS LAS VISTA DE VISTAS DE FUNCIONES A CLASES
   
class Crear_empresa(SuccessMessageMixin,CreateView):
    model = EmpresaProveedor
    template_name = 'CRUD_empresas.html'
    form_class = EmpresaCrear
    success_url = reverse_lazy('perfil:empresas_list')
    def get_success_message(self,cleaned_data):
        print cleaned_data
        return 'Datos guardados'




class Listado_empresas(ListView):
    ordering = ['id']   
    model = EmpresaProveedor
    context_object_name = 'empresas'
    paginate_by = 6
    template_name = 'listado_empresas.html'
    
 

class Editar_empresa(UpdateView):
    model = EmpresaProveedor
    template_name = 'CRUD_empresas.html'
    form_class = EmpresaCrear
    success_url = reverse_lazy('perfil:empresas_list')

class Eliminar_empresa(DeleteView):
    model = EmpresaProveedor
    template_name = 'empresa_delete.html'
    success_url = reverse_lazy('perfil:empresas_list')

base_sistema/app/perfil/templates/CRUD_Perfiles.html
{%extends 'empresas_index.html' %}{# heredando de base_menu #}
{% load crispy_forms_tags %}
{% block content %}
		<div  class="row col-md-5 offset-1">
			
			<div  id="formularios" class="fondo ">
			
				<form method="post">
					{% csrf_token %}{# token de seguridad #}
			

				<div  id="formularios" class="fondo ">
					<div class="card-header"> 
						<h4>Crear Contacto de Usuario</h4>
					</div>
					{{form|crispy}}
					<div class="card-footer text-muted">
						<p> Asegurese de guardar correctamente los datos...</p>
					  </div>
					  <br>
						<button type="submit" class="botones btn btn-primary btn-block">Registrar</button>
						
				</div>
				</form>
				
    		</div>
		</div>
	   
{% endblock content %}

base_sistema/app/perfil/templates/CRUD_empresas.html
{%extends 'empresas_index.html' %}
{% load crispy_forms_tags %}

{% load staticfiles %}

  {%block content%}
		
	<div  class="col-md-6 offset-2">
			
		<div  id="formularios" class="fondo ">
				<div class="card-header"> 
                        <h4>Empresa</h4>
                    </div>
			<form method="post" class="card-body">
				{% csrf_token %}
				{{form|crispy}}

				<div class="container">
					<button  type="submit" class="botones btn btn-primary btn-block">Guardar</button>
				</div>
			</form>
			
						
		</div>
				
	</div>
{% endblock content %}

base_sistema/app/perfil/templates/CRUD_usuarios.html
{%extends 'index_perfil.html' %}{# heredando de base_menu #}
{% load crispy_forms_tags %}

{% block content %}
		<div  class="col-md-5 offset-1">
			
		<div  id="formularios" class="fondo ">
			
			<form method="post">
				{% csrf_token %}{# token de seguridad #}
		

				<form action="/action_page.php">
				<div class="container ">
					<h1><center>Registrar Usuario</center> </h1>
					<p>Por favor, rellene este formulario para crear una cuenta usuario.</p>
					<hr>

					

				<fieldset>
				
					
					<div class="form-group">
					{{form|crispy}}
					</div>
					<hr>
					<p>By creating an account you agree to our <a href="#">Terminos y privacidad</a>.</p>

					<button type="submit" class="botones btn btn-primary btn-block ">Registrar</button>
				</div>
				
				<!-- <div class="container signin">
					<p>Already have an account? <a href="#">Sign in</a>.</p>
				</div> -->
			</form>
			</div>
    		</div>
		</div>
	   
{% endblock content %}

base_sistema/app/perfil/templates/contactos_proveedores.html
{% extends 'empresas_index.html' %}

{% block content %}
<div class="jumbotron col-md-8  offset-1">
        <h1 class="display-5"><center> <strong> Consulta de contactos de proveedores</strong></center></h1>
        <br>
        <table class="table  table-sm table-hover table-responsive " >
                <thead>
                    <tr class="table-primary">
                        <th>Id</th>
                    	<th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Usuario</th>
                        <th>Empresa</th>
                        <th>NIT</td>
                        <th>Telefono</th>
                        <th>Direccion</th>
                       
                        
                     </tr>
                 </thead>
     
           
            <tbody>
                    {% if proveedores%}
                    {% for proveedor in proveedores%}
                <tr>
                    <td> {{proveedor.id}}</td>
                    <td> {{proveedor.usuario.first_name}}</td>
                    <td> {{proveedor.usuario.last_name}}</td>
                    <td> {{proveedor.usuario.username}}</td>
                    <td> {{proveedor.empresa_proveedor.nombre_empresa}}</td>
                    <td> {{proveedor.nit}}</td>
                    <td> {{proveedor.telefono}}</td>
                    <td> {{proveedor.direccion}}</td>
                    
                   
                    
                  
                </tr>
               

                {%endfor%}
                {%else%}
                <div class="container col-md-8  offset-1">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat molestiae commodi doloribus fugiat sit blanditiis neque, exercitationem doloremque quod facilis accusamus asperiores, nobis ducimus distinctio saepe assumenda hic amet numquam.
                </div>
                    
                {%endif%}
            </tbody>
            <div class="">
                    <td>
                    
                    <a class="botones btn btn-primary" href="{% url 'perfiles_pdf' %}">Generar Reporte</a>
                    </td>
                   <td>
                        <a class="botones btn btn-success" href="{% url 'perfil:proveedores_crear' %}">Crear Contacto</a>
                   </td>
                </div>
        
        </table>

    </div>
{% endblock content %}

base_sistema/app/perfil/templates/empresa_delete.html
{% extends 'empresas_index.html' %}
{% block content %}
<div class="row container-fluid col-md-5 offset-2">
	
	<style>
		.delete{
			background-color: rgb(227, 226, 241);
			border-radius: 5px;
			padding: 15px;
			box-shadow: 5px 5px 5px #AFACAD;
            
	
			}			
			
	</style>

	     <div class="">
	      <div class="delete">
			    <form method="post" >

			    	{% csrf_token %}{# token de seguridad #}
			    	<h2><p class="help-block"></p>¿Desea eliminar el registro {{object.nombre_empresa}} de la base de datos?</p></h2>
			    	<button class="botones btn btn-danger"type="submit">Si</button>
			    	<a class="btn btn-default"href="{% url 'perfil:empresas_list' %}">Cancelar</a>
			    </form>
		   </div> 
	     </div>	
	     
</div>  
  
{% endblock content %}

base_sistema/app/perfil/templates/empresas_index.html
{% extends 'base/base_menu.html' %}
{% load staticfiles %}
	
{% block title %}Empresas{% endblock %}
{% block side_bar %}
<div class="offset-2">
<ul class="nav nav-pills flex-column  col-md-3 ">
    <li class="nav-item border border-secondary">
        <a class="nav-link fondo border border-secondary" href="#"><h5><center> Empresas</center></h5></a>
    </li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item" href="{% url 'perfil:empresas_list' %}">Listado de Empresas</a>
    </li>    
    <li class="nav-item border border-secondary">
        <a class="dropdown-item " href="{% url 'perfil:empresa' %}">Registrar Empresa</a>
    </li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item " href="{% url 'perfil:proveedores_list' %}">Contacto de Proveedores</a>
    </li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item" href="{% url 'productos:buscar_producto_por_empresa' %}">Stock por empresa</a>
    </li>
      </div>
    
  </ul>
  
</div>
{% endblock %}

{% block content %}
<div class="jumbotron col-md-8  offset-1">
  <h4 class="display-4">Consulta de empresas y contactos!</h4>
  <li class="lead">Como puedes encontrar nuesto manual de usuario.</li>
  <hr class="my-4">
  <li class="lead">Si esta logeado recuerda cerrar secion al terminar tu trabajo.</li>
  <br>
  <p class="lead">
    <a class="botones btn btn-primary btn-lg" href="#" role="button">Leer mas...</a>
  </p>
</div>
<style>
.jumbotron{
    border-radius: 10px;
}
</style>
{% endblock content %}

base_sistema/app/perfil/templates/index_perfil.html
{% extends 'base/base_menu.html' %}
{% load staticfiles %}
	
{% block title %}Empresas{% endblock %}

{% block side_bar %}
<div class="offset-2">
<ul class="nav nav-pills flex-column  col-md-3 ">
    <li class="nav-item border border-secondary">
        <a class="nav-link fondo border border-secondary" href="#"><h5><center>Usuarios</center></h5></a>
    </li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item" href="{% url 'perfil:crear' %}">Crear Usuario</a>
    </li>    
    <li class="nav-item border border-secondary">
        <a class="dropdown-item " href="{% url 'perfil:usuario_list' %}">Lista de Usuarios</a>
    </li>
    
      </div>
    
  </ul>
  
</div>
{% endblock %}

{% block content %}
<div class="jumbotron col-md-8  offset-1">
  <h4 class="display-4">Consulta de Usuarios</h4>
  <li class="lead">Como puedes encontrar nuesto manual de usuario.</li>
  <hr class="my-4">
  <li class="lead">Si esta logeado recuerda cerrar secion al terminar tu trabajo.</li>
  <br>
  <p class="lead">
    <a class="botones btn btn-primary btn-lg" href="#" role="button">Leer mas...</a>
  </p>
</div>
<style>
.jumbotron{
    border-radius: 10px;
}
</style>
{% endblock content %}

base_sistema/app/perfil/templates/lista_usuarios.html
{% extends 'index_perfil.html' %}
 {% load staticfiles %}



{% block content %}

{% block extraheader %}
    
    {% endblock extraheader %}


<table class="table  table-sm table-hover table-responsive col-md-9  offset-1" >
    <thead>
      <tr class="table-primary">
            <th>Id</th>
            <th>Usuario</th>
            <th>Fecha de Creacion</th>
            <th>Ultima fecha de ingreso</th>
            
          </tr>
        </thead>


        <tbody>
          <tr>

              {% if object_list%}
                  {% for usuario in object_list%}
              <td> {{usuario.id}}</td>
              <td> {{usuario.username}}</td>
              <td> {{usuario.date_joined}}</td> 
              <td> {{usuario.last_login}}</td>     
     
          </tr>
          {%endfor%}

      {%else%}
      <h1>No hay ningun Usuario Registrado</h1>
      
                      
            
      {%endif%}
        </tbody>
      </table>
   <div class="container col-md-3 offset-8">
      <a class="botones btn btn-success" href="{% url 'perfil:crear' %}">Crear usuario</a>

   </div>

{% endblock content %}

base_sistema/app/perfil/templates/listado_empresas.html
{% extends 'empresas_index.html' %}


{% block content %}


<table class="table table-sm table-hover table-responsive col-md-8  offset-1" >
    <thead>
      <tr class="table-primary">
        
        <th>Id</t>
        <th>NOMBRE</th>
        <th>NIT</td>
        <th>TELEFONO</th>
        <th>CONTACTO EMAIL</th>
        <th>Opcion 1</th>
        <th>Opcion 2</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        
          {% if object_list %}
    {% for empresa in object_list %}
    <tr>
        <td> {{empresa.id}}</td>
        <td> {{empresa.nombre_empresa|upper}}</td>
        <td> {{empresa.nit}}</td>
        <td> {{empresa.telefono}}   </td>
        <td> {{empresa.contacto_email}}</td>
       
        <td>
          <a class="botones btn btn-primary" href="{% url 'perfil:empresas_edit' empresa.id%}">Editar</a>
        </td>
        <td>
            <a class="botones btn btn-danger" href="{% url 'perfil:empresas_delete' empresa.id%}">Eliminar</a>

        </td>
        
      
    </tr>
   

    {%endfor%}
    {%else%}
    <h1>No hay ningun Usuario Registrado</h1>
    <td>vacio</td>
     <td>vacio</td>
     <td>vacio</td>
     <td>vacio</td>
     <td>vacio</td>
                    
         
    {%endif%}
</tbody>
</table>




  {% if is_paginated %}
<div class="col md-3 offset-4">
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li  class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">ANTERIOR</a></li>
    {% else %}
      <li class="disabled page-item" > <span class="page-link">ANTERIOR</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}  
        <li><a class="page-link " href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a class="page-link " href="?page={{ page_obj.next_page_number }}">SIGUIENTE</a></li>
    {% else %}
    <li class="disabled page-item" > <span class="page-link">SIGUIENTE</span></li>
    {% endif %}
  </ul>
</nav>
</div>
{% endif %}

  
          
{% endblock content %}