base_sistema/app/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from app.productos.views import index_productos,Listado_producto,Editar_producto,Borrar_producto,\
Listado_pedido,Editar_pedido,Borrar_producto_pedido,Listado_categorias,inventario_view,Crear_producto,Detalles_producto,Crear_pedido

from django_filters.views import FilterView
from . filters import ProductoFilter
	
#la vista productos_view del archivo views.py

urlpatterns = [
    url(r'^index$', login_required(index_productos), name='index_productos'),#parametros de la url,index sera el
    #segundo patron que buscara django el primer patron a buscar es 'productos '
    #que es el que se encuentra dentro de el archivo de URLS  globales
   	url(r'^nuevo$', login_required(Crear_producto.as_view()), name='productos_nuevo'),
    url(r'^pedido$', login_required(Crear_pedido.as_view()), name='pedido_nuevo'),
   	url(r'^listar$', login_required(Listado_producto.as_view()), name='productos_listar'),
   	url(r'^editar/(?P<pk>\d+)/$', login_required(Editar_producto.as_view()), name='productos_editar'),
	url(r'^productos_detail/(?P<pk>\d+)/$', login_required(Detalles_producto.as_view()), name='productos_detail'),
   	url(r'^buscar_producto$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='producto_filtro_list.html')), name='buscar_producto'),
   	url(r'^eliminar/(?P<pk>\d+)/$', login_required(Borrar_producto.as_view()), name='productos_eliminar'),
   	url(r'^pedido_delete_producto/(?P<pk>\d+)/$', login_required(Borrar_producto_pedido.as_view()), name='pedido_delete_producto'),
   	url(r'^pedido_edit/(?P<pk>\d+)/$', login_required(Editar_pedido.as_view()) , name='pedido_edit'),#debe tener un id
   	#de producto hasta crear los botones en el template
	# url(r'^pedido_filtro$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='producto_id_filtro.html')), name='pedido_filtro'),
   	url(r'^pedido_list$', login_required(Listado_pedido.as_view()), name='pedido_list'),
    url(r'^categorias_list$', login_required(Listado_categorias.as_view()), name='categorias_list'),
    url(r'^inventario_view$', login_required(inventario_view), name='inventario_view'),
	url(r'^buscar_producto_por_empresa$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='stock_por_empresa_filtro_list.html')), name='buscar_producto_por_empresa'),

   	

]	

base_sistema/base_sistema/urls.py
# from django.conf.urls import url,include
# from django.contrib import admin
# from django.contrib.auth.views import login

# # from django.contrib.auth import views as auth_views
# # from django.views.generic.base import TemplateView


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from base_sistema.views import pedidoPDF,empresasPDF,perfilPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),#importando las urls del 
    #admin que trae django por defecto
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logout.html'}, name='logout'),
    url(r'^productos/', include('app.productos.urls', namespace="productos")),#name_space
    #son los nombres de las urls globalesy 'app.productos.urls' es la ruta del archivo  
    url(r'^perfil/', include('app.perfil.urls',namespace="perfil")),
    ## REPORTES GENERALES
    url(r'^pedido_pdf/',pedidoPDF.as_view(), name='pedido_pdf'),
    url(r'^empresas_pdf/',empresasPDF.as_view(), name='empresas_pdf'),
    url(r'^perfiles_pdf/',perfilPDF.as_view(), name='perfiles_pdf'),


]

base_sistema/app/productos/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from django.db import models


from app.perfil.models import EmpresaProveedor

#poner dos forek uno a productos y otro a categorias
class Categoria(models.Model):
	"""docstring for Tipo_producto"""
	nombre = models.CharField(max_length=50)

	def __unicode__(self):
		return '{}'.format(self.nombre)
class Factor_empaque(models.Model):
	"""docstring for Tipo_producto"""
	factor_de_empaque = models.CharField(max_length=30,blank=False)

	def __unicode__(self):
		return '{}'.format(self.factor_de_empaque)


#forek hacia categorias
class Producto(models.Model):
	#creando atributos
	nombre = models.CharField(max_length = 50)#el tipo de campo charfield recibe de
	#parametro por obligacion la propiedad o argumento max_length
	descripcion = models.TextField(blank=True, null=True)#texto plano
	marca = models.CharField(max_length=50)
	precio_unitario = models.DecimalField(decimal_places=2, max_digits=10000)
	inventario=models.IntegerField( default=0)
	factor_de_empaque = models.ForeignKey(Factor_empaque, null=True)
	fecha_compra = models.DateTimeField(auto_now_add=True,)
	empresa_proveedor = models.ForeignKey(EmpresaProveedor, null=True, blank= False)#relacion de uno a muchos
	#un proveedor puede tener muchos productos
	#o muchos productos pueden pertenecer a un mismo proveredor
	categoria = models.ManyToManyField(Categoria, blank=True)#relacion de muchos a muchos
	#muchos productos puede pertenecer de uno o mas categorias
	

	def __unicode__(self):#funcion para que se nos devuelva el nombre y no el objeto
	#que hemos registrado
		return '{}{}'.format(self.nombre,self.id)#en este caso la llave foranea del proveedor
		#y que nos muestre en un select el nombre de la empresa
		#creando modelo para realizar un pedido

class Pedido_mercaderia(models.Model):# mas adelante agregare un numero de pedido, el id del producto
# y fecha en que se realiza el pedido
	producto_a_pedir = models.OneToOneField(Producto, blank=False,default="")
	fecha_compra= models.DateTimeField(auto_now_add=True,)
	cantidad = models.IntegerField(blank= False)
	# empresa = models.ForeignKey(EmpresaProveedor, blank=False,default="")

	class Meta:
		verbose_name = "Pedido_Producto"
		verbose_name_plural = "Pedido_Productos"
	def __unicode__(self):#
		return '{}'.format(self.producto_a_pedir)#

base_sistema/app/productos/forms.py
from django import forms
from app.productos.models import Producto,Pedido_mercaderia

#creando la clase de el formulario para Registar datos
# desde nel template productos_form.html
class ProductoForm(forms.ModelForm):#esta es la clase que se crea para poder
#nuestra vista
	#la clase ProductoForm esta heredando todas los metos de form.ModelForm
	class Meta:#modelo del cual vamos a crear nuestro formulario
		model = (Producto)#guardando el modelo Producto dentro de la variable model
		fields = [# la clase  meta nos sirve para usar los metadatos en nuestro modelo.
		#ordenar dato entre otras cosas

		#colocando todos los campos del modelo Productos
		#para utilizarlos
			'nombre',
			'descripcion',
			'marca',
			'precio_unitario',
			'inventario',
			'factor_de_empaque',			
			'empresa_proveedor',
			'categoria',


		]
		# creando los label de nuestro formulario
		# o la etiquetas que contendra nuestro formulario
		labels = {
			'nombre':			'Nombre',
			'descripcion':		'Descripcion',
			'marca':			'Marca',
			'precio_unitario':	'Precio/unidad',
			'factor_de_empaque': 'factor_de_empaque',
			'inventario'		: 'inventario',
			# 'fecha_compra':		'Fecha de Compra',
			'empresa_proveedor':		'Proveedor',
			'categoria':	'Categoria',

		}
		widgets	= {
		# #Creando los widgets
		# #El widget maneja la representacion del HTML 
		# #y la extraccion de datos de un diccionario GET / POST que corresponde al widget.
		# #dan la forma html

		 	'nombre':forms.TextInput(attrs={'class':'form-group'}),#como atributo madamos 
		 	#la clase from control de boostrap
		 	'descripcion':forms.Textarea(attrs={'cols': 56, 'rows': 5}),
		 	'marca':forms.TextInput(attrs={'class':'form-group'}),
		 	'precio_unitario':forms.TextInput(attrs={'class':'form-group'}),
		 	'factor_de_empaque':forms.Select(attrs={'class':'form-group'}),
		 	'inventario':forms.TextInput(attrs={'class':'form-group'}),
		 	# 'fecha_compra':forms.TextInput(attrs={'class':'form-control'}),
		 	'empresa_proveedor':forms.Select(attrs={'class':'form-control'}),#proveedor es una llave foranea
		 	'categoria':forms.CheckboxSelectMultiple(attrs={'class':'form-check-inline'}),#tipo_producto es un atributo con una relacion
		# 	#de muchos a muchos, y se utiliza un CheckboxSelectMultiple

		}
		# #form para hacer pedidos de productos

class Pedido_mercaderiaForm(forms.ModelForm):#esta es la clase que se crea para poder
#nuestra vista
	#la clase ProductoForm esta heredando todas los metos de form.ModelForm
	class Meta:#modelo del cual vamos a crear nuestro formulario
		model = Pedido_mercaderia #guardando el modelo Producto dentro de la variable model
		fields = [# la clase  meta nos sirve para usar los metadatos en nuestro modelo.
		#ordenar dato entre otras cosas

		#colocando todos los campos del modelo Productos
		#para utilizarlos
			#agregar campo de numero de orden
			'producto_a_pedir',
			'cantidad',
			# 'empresa'
			
			


		]
		
		labels = {
			'producto_a_pedir':		'Elegir Mercaderia',
			'cantidad':				'Cuantos Articulos desea pedir?',
			# 'empresa' :				'EMPRESA'
		
		}
		widgets	= {
		
			'producto_a_pedir':forms.Select(attrs={'class':'form-control'}),
			'cantidad':forms.TextInput(attrs={'class':'form-control'}),
			'empresa_proveedor':forms.Select(attrs={'class':'form-control'}),
		}

base_sistema/app/productos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from app.productos.forms import ProductoForm,Pedido_mercaderiaForm #importando el formulario 
from app.productos.models import Producto,Pedido_mercaderia, Categoria#importando modelo Producto
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import ProductoFilter





#Vistas APP PRODUCTO
def index_productos(request):#con request  se le indica que reciba la peticion
	return render(request, 'index_productos.html')
   

def inventario_view(request):
    return render(request, 'index_inventario.html')

class Listado_producto(ListView):
	ordering = ['empresa_proveedor']   
	model = Producto
	template_name = 'lista_productos.html'
	paginate_by = 6

  
class Crear_producto(SuccessMessageMixin,CreateView):
    model = Producto
    template_name = 'productos_form.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:productos_listar')
    def get_success_message(self,cleaned_data):
        print cleaned_data
        return 'Datos guardados'

class Editar_producto(UpdateView):
    model = Producto
    template_name = 'productos_form.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:productos_listar')
class Borrar_producto(DeleteView):
    model = Producto
    template_name = 'productos_delete.html'
    success_url =reverse_lazy('productos:productos_listar')

class Detalles_producto(DetailView):
    model = Producto
    queryset = Producto.objects.all()#ordenando
    template_name = 'detalles_productos.html'
#Creando vista para hacer pedidos

class Crear_pedido(CreateView):
	model = Pedido_mercaderia
	template_name = 'CRUD_pedido.html'
	form_class = Pedido_mercaderiaForm
	success_url = reverse_lazy('productos:pedido_list')
class Editar_pedido(UpdateView):
    model = Pedido_mercaderia
    template_name = 'CRUD_pedido.html'
    form_class = Pedido_mercaderiaForm
    success_url = reverse_lazy('productos:pedido_list')


class Listado_pedido(ListView):
    ordering = ['id']   
    model = Pedido_mercaderia
    # queryset= Pedido_mercaderia.objects.filter()
    template_name = 'pedido_reporte.html'
  

class Borrar_producto_pedido(DeleteView):
    model = Pedido_mercaderia
    template_name = 'producto_pedido_delete.html'
    success_url =reverse_lazy('productos:pedido_list')

class Listado_categorias(ListView):
    	
    ordering = ['id']   
    model = Categoria
    template_name = 'lista_categorias.html'



# def search(request):
#     producto_list = Producto.objects.all()
#     producto_filter = ProductoFilter(request.GET, queryset=producto_list)
#     return render(request, 'CRUD_pedido.html', {'filter': producto_filter})

base_sistema/app/productos/templates/CRUD_pedido.html
{% extends 'index_inventario.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="card border-primary offset-1 col-md-6 fondo">
	<div class="card-body">
		<h4 class="card-title card border-primary">Pedido</h4>
		<p class="card-text text-center card border-primary col-md-10 offset-1">Compra de articulos</p>
		<form method="post" class="card-body offset-1">
				{% csrf_token %}
					{{form|crispy}}
			
				<br>
				<button class="botones btn-primary offset-10"type="submit">PEDIR</button>
			
		</form>
	</div>
	
</div>
 {% endblock content %}

base_sistema/app/productos/templates/detalles_productos.html
{% extends 'index_productos.html' %} {% load staticfiles %}
{% block extraheader %}


{% endblock extraheader %} {% block content %}

<div class="col-md-8 offset-1">

    <div id="formularios" class="fondo ">
        <div class="card-header">
            <h4>Articulo Nuevo</h4>
        </div>
        <form method="post" class="card-body">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Nombre Articulo</span>
                </div>
                <input name="nombre" type="text" value="{{object.nombre}}" class="form-control" aria-label="Default"
                    aria-describedby="inputGroup-sizing-default" disabled>
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Detalles del Articulo</span>
                </div>
                <input name="nombre" type="text" value="{{object.descripcion}}" class="form-control" aria-label="Default"
                    aria-describedby="inputGroup-sizing-default" disabled>
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Marca</span>
                </div>
                <input name="marca" type="text" value="{{object.marca}}" class="form-control" aria-label="Default"
                    aria-describedby="inputGroup-sizing-default" disabled>
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Precio Unitario</span>
                </div>
                <input name="precio_unitario" type="text" value="{{object.precio_unitario}}" class="form-control"
                    aria-label="Default" aria-describedby="inputGroup-sizing-default" disabled>
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Inventario actual</span>
                </div>
                <input name="inventario" type="number" value="{{object.inventario}}" class="form-control" aria-label="Default"
                    aria-describedby="inputGroup-sizing-default" disabled>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Factor de empaque</span>
                </div>
                <input name="factor_de_empaque" type="text" value="{{object.factor_de_empaque}}" class="form-control"
                    aria-label="Default" aria-describedby="inputGroup-sizing-default" disabled>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Empresa Proveedor</span>
                </div>
                <input name="empresa_proveedor" type="text" value="{{object.empresa_proveedor}}" class="form-control"
                    aria-label="Default" aria-describedby="inputGroup-sizing-default" disabled>
            </div>
            <div class="input-group mb-3">
                <br>
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Categoria</span>
                </div>

                <input name="categoria" type="text" value="{% for categoria in producto.categoria.all %}| {{ categoria }}|{% endfor %}"
                    class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" disabled>
            </div>
            <br>
            <br>


            <a class="botones btn btn-info" href="{% url 'productos:productos_listar' %}">Ir a catalogo de productos</a>


    </div>
    <style>
        .card-footer,
        .card-header {
            border-radius: 10px;
        }
    </style>
    </form>






</div>

</div>
<!-- <script src="{% static 'TableFilter/tablefilter.js'%}"></script> -->


<!-- <script src="{% static 'js/fecha.js'%}"></script> -->
<!--llamando el archivo de fitro DataTables-->

{% endblock %}

base_sistema/app/productos/templates/index_inventario.html
{% extends 'base/base_menu.html' %}
{% load staticfiles %}
	
{% block title %}Inventario{% endblock %}

{% block side_bar %}
<div class="offset-2">
<ul class="nav nav-pills flex-column  col-md-3 ">
  <li class="nav-item border border-secondary">
    <a class="nav-link fondo border border-secondary" href="{% url 'productos:index_productos' %}"><h5><center>Inventarios</center></h5></a>
</li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item " href="#"> Productos fuera de stock</a>
    </li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item " href="#"> Ver pedidos</a>
    </li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item" href="{% url 'productos:pedido_nuevo' %}">Realizar Pedidos</a>
    </li>    
    <li class="nav-item border border-secondary">
        <a class="dropdown-item " href="#">Reportes</a>
    </li>
    <li class="nav-item border border-secondary">
        <a class="dropdown-item " href="{% url 'productos:pedido_list' %}">Pedido Creado</a>
    </li>
    
      </div>
    
  </ul>
  
</div>
{% endblock %}

{% block content %}
<div class="jumbotron col-md-8  offset-1">
  <h4 class="display-4">Consulta de Inventario</h4>
  <li class="lead">Como puedes encontrar nuesto manual de usuario.</li>
  <hr class="my-4">
  <li class="lead">Si esta logeado recuerda cerrar secion al terminar tu trabajo.</li>
  <br>
  <p class="lead">
    <a class="botones btn btn-primary btn-lg" href="#" role="button">Leer mas...</a>
  </p>
</div>
<style>
.jumbotron{
    border-radius: 10px;
}
</style>
{% endblock content %}

base_sistema/app/productos/templates/index_productos.html
{% extends 'base/base_menu.html' %}

{% block title %}Productos{% endblock %}


{% block side_bar %}

<div class="offset-2">
  <ul class="nav nav-pills flex-column  col-md-3 ">
    <li class="nav-item border border-secondary">
      <a class="fondo nav-link  border border-secondary" href="{% url 'productos:index_productos' %}">
        <h5>
          <center> Productos</center>
        </h5>
      </a>
    </li>
    <li class="nav-item border border-secondary">
      <a class="dropdown-item" href="{% url 'productos:productos_listar' %}">Catalogo de Productos</a>
    </li>

    <li class="nav-item border border-secondary">
      <a class="dropdown-item " href="{% url 'productos:buscar_producto' %}">Ver por categorias</a>
    </li>
    <li class="nav-item border border-secondary">
      <a class="dropdown-item" href="{% url 'productos:productos_nuevo' %}">Nuevo articulo</a>
    </li>
</div>

</ul>

</div>




{% endblock side_bar%}


{% block content %}
<div class="jumbotron col-md-8  offset-1">
  <h4 class="display-4">Consulta de Productos</h4>
  <li class="lead">Como puedes encontrar nuesto manual de usuario.</li>
  <hr class="my-4">
  <li class="lead">Si esta logeado recuerda cerrar secion al terminar tu trabajo.</li>
  <br>
  <p class="lead">
    <a class="botones btn btn-primary btn-lg" href="#" role="button">Leer mas...</a>
  </p>
</div>
<style>
  .jumbotron {
    border-radius: 10px;
  }
</style>
{% endblock content %}

base_sistema/app/productos/templates/lista_productos.html
{% extends 'index_productos.html' %} {% load staticfiles %} 
{% block content %} 
{% block extraheader %}
<link rel="stylesheet" href="{% static 'css/filtro.css' %}">
<script src="{% static  'Jquery/jquery-1.12.4.js' %}"></script>
<script src="{% static  'Jquery/datatables.min.js' %}"></script>
<script src="{% static  'Jquery/filtro.js' %}"></script>

{% endblock extraheader %}


<table class="botones table  table-sm table-hover table-responsive col-md-9  offset-1" >
    <thead>
      <tr class="table-primary">
          <th>Codigo</th>
          <th>Nombre</th>
          {% comment %} <th>Descripcion</th> {% endcomment %}
          <th>Marca</th>
          <th>Precio/Unidad</th>
          <!-- <th>Iva</th>
          <th>Precio Iva incluido</th> -->
          {% comment %} <th>U/caja</th> {% endcomment %}
          <th>Stock</th>
          <th>Empresa</th>
          <th>Categorias</th>
          <th>Opcion 1</th>
          <th>Opcion 2</th>
          <th>Opcion 3</th>
        </tr>
      </thead>

      <tbody>


        <tr>


          {% if object_list %} {% for producto in object_list %}
          <td> {{producto.id}}</td>
          <td> {{producto.nombre}}</td>

          {% comment %} <td> {% if producto.descripcion %}{{producto.descripcion}}{%else%}No hay descripcion...{%endif%}</td> {% endcomment %}
          <td> {{producto.marca}} </td>
          <td> {{producto.precio_unitario}}</td>
          
          {% comment %} <td> {{producto.factor_de_empaque}}</td> {% endcomment %}
          <td> {{producto.inventario}}</td>
          <td> {{producto.empresa_proveedor}}</td>
          <td> {% for categoria in producto.categoria.all %} 
          |{{ categoria }}|
           {% endfor %}
          </td>
          <td>
              <a class="botones btn btn-primary" href="{% url 'productos:productos_editar' producto.id%}">Editar</a>
          </td>
          <td>
              <a class="botones btn btn-danger" href="{% url 'productos:productos_eliminar' producto.id%}">Eliminar</a>
          </td>
          <td>
              <a class="botones btn btn-info" href="{% url 'productos:productos_detail' producto.id%}">Detalles</a>
          </td>
        </tr>


        {%endfor%} {%else%}
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        <td>vacio</td>
        
        
        
        {%endif%}
      </tbody>
    </table>

  {% if is_paginated %}
<div class="col md-3 offset-4">
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li  class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">ANTERIOR</a></li>
    {% else %}
      <li class="disabled page-item" > <span class="page-link">ANTERIOR</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}  
        <li><a class="page-link " href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a class="page-link " href="?page={{ page_obj.next_page_number }}">SIGUIENTE</a></li>
    {% else %}
    <li class="disabled page-item" > <span class="page-link">SIGUIENTE</span></li>
    {% endif %}
  </ul>
</nav>
</div>
{% endif %}


  </div>
</div>

 <br>
    <div class="col-md-8 offset-7 ">
      <td>
        <a class="botones btn btn-success" href="{% url 'productos:productos_nuevo' %}">Nuevo Producto</a>
      </td>
        <button type="button" class="botones btn btn-primary" id="my_button" onclick="mostrar()">Informacion</button>

      </div>
   
  <div class="col-md-8 offset-3 ">
      <div id="my_table">
        <h3><p class="help-block">Esta tabla muestra los productos disponibles en el catalogo</p></h3>
      </div>

  </div>
  </div>
</div>

<br>
<br>







<script type="text/javascript">
  $("#my_table").hide(); //lo primero que ejecutara

  function mostrar() {

    let text = "";
    //para comparar string en javascript
    //se utiliza triple '='
    if ($("#my_button").text() === "Informacion") {
      $("#my_table").show();
      text = "Cerrar";

    } else {
      $("#my_table").hide();
      text = "Informacion";

    }
    $("#my_button").html(text);
  }
</script>



{% endblock content %}

base_sistema/app/productos/templates/pedido_reporte.html
{% extends 'index_inventario.html' %}

{% block content %}

<table class="botones table  table-sm table-hover table-responsive col-md-8  offset-1" >
    <thead>
      <tr class="table-primary">
                
                        <th>Codigo </th>
                        <th>Producto</th>
                        <th>Fecha De Pedido</th>
                        <th>Unidades/Pedidas</th>
                       
                        <th>Opcion 1</th>
                        <th>Opcion 2</th>
                        

                        
                     </tr>
                 </thead>
     
           
            <tbody>
                {% if object_list%}
                {% for pedido in object_list%}
                <tr class="text-center"">
                    <td> {{pedido.producto_a_pedir.id}}</td>{# id del articulo y no del pedido #}
                    <td> {{pedido.producto_a_pedir}}</td>
                    <td> {{pedido.fecha_compra}}</td>
                    <td>{{pedido.cantidad}}</td>
                   
                   
                    <td> <a class="botones btn btn-primary" href="{% url 'productos:pedido_edit' pedido.id%}">Editar</a>
                   </td>
                   <td>
                        <a class="botones btn btn-danger" href="{% url 'productos:pedido_delete_producto' pedido.id%}">Eliminar</a>

                   </td>
                  
                </tr>
                  <style>
                  .text-center {text-align: center} /*For center align*/
                  </style>
                    
               

                {%endfor%}
                {%else%}
                <h1>No hay ningun Producto en pedidos</h1>
                 <td>vacio</td>
                 <td>vacio</td>
                 <td>vacio</td>
                 <td>vacio</td>
                 <td>vacio</td>
                
                 
                     
                {%endif%}
            </tbody>
        </table>
        
                <div class="col-md-9  offset-8">
                     <td>
                        <a class="botones btn btn-success" href="{% url 'productos:pedido_nuevo' %}">Nuevo Producto</a>
                     </td>
                      <a class="botones btn btn-primary" href="{% url 'pedido_pdf' %}">Generar Reporte</a>
                 
            
                 </div>
         
    </div>    
</div>
{% endblock content %}