base_sistema/app/perfil/urls.py
from django.conf.urls import url
from .views import RegistroUsuario,index_perfils,empresas_index, \
Usuario_ListView,proveedores_list,Listado_empresas,Crear_empresa,Editar_empresa,Eliminar_empresa,PerfilCrear
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^index$', login_required(index_perfils), name='index'),
    url(r'^crear$', login_required(RegistroUsuario.as_view()), name='crear'),  # pasando los parametros de la url,index sera el
    # segundo patron que buscara django el primer patron a buscar es 'productos '
    # que es el que se encuentra dentro de el archivo de URLS  globales
    url(r'^usuario_list$', Usuario_ListView.as_view(), name='usuario_list'),
    url(r'^empresas_index$', empresas_index, name='empresas_index'),
    url(r'^empresa$', Crear_empresa.as_view(), name='empresa'),
    url(r'^empresas_list$', Listado_empresas.as_view(), name='empresas_list'),
    url(r'^editar/(?P<pk>\d+)/$',Editar_empresa.as_view(),name='empresas_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', Eliminar_empresa.as_view(), name='empresas_delete'),
    ##proveedores
    url(r'^proveedores_crear$', PerfilCrear.as_view(), name='proveedores_crear'),
    url(r'^proveedores_list$', proveedores_list, name='proveedores_list'),
   


]

base_sistema/app/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from app.productos.views import index_productos,Listado_producto,Editar_producto,Borrar_producto,\
Listado_pedido,Editar_pedido,Borrar_producto_pedido,Listado_categorias,inventario_view,Crear_producto,Detalles_producto,Crear_pedido

from django_filters.views import FilterView
from . filters import ProductoFilter
	
#la vista productos_view del archivo views.py

urlpatterns = [
    url(r'^index$', login_required(index_productos), name='index_productos'),#parametros de la url,index sera el
    #segundo patron que buscara django el primer patron a buscar es 'productos '
    #que es el que se encuentra dentro de el archivo de URLS  globales
   	url(r'^nuevo$', login_required(Crear_producto.as_view()), name='productos_nuevo'),
    url(r'^pedido$', login_required(Crear_pedido.as_view()), name='pedido_nuevo'),
   	url(r'^listar$', login_required(Listado_producto.as_view()), name='productos_listar'),
   	url(r'^editar/(?P<pk>\d+)/$', login_required(Editar_producto.as_view()), name='productos_editar'),
	url(r'^productos_detail/(?P<pk>\d+)/$', login_required(Detalles_producto.as_view()), name='productos_detail'),
   	url(r'^buscar_producto$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='producto_filtro_list.html')), name='buscar_producto'),
   	url(r'^eliminar/(?P<pk>\d+)/$', login_required(Borrar_producto.as_view()), name='productos_eliminar'),
   	url(r'^pedido_delete_producto/(?P<pk>\d+)/$', login_required(Borrar_producto_pedido.as_view()), name='pedido_delete_producto'),
   	url(r'^pedido_edit/(?P<pk>\d+)/$', login_required(Editar_pedido.as_view()) , name='pedido_edit'),#debe tener un id
   	#de producto hasta crear los botones en el template
	# url(r'^pedido_filtro$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='producto_id_filtro.html')), name='pedido_filtro'),
   	url(r'^pedido_list$', login_required(Listado_pedido.as_view()), name='pedido_list'),
    url(r'^categorias_list$', login_required(Listado_categorias.as_view()), name='categorias_list'),
    url(r'^inventario_view$', login_required(inventario_view), name='inventario_view'),
	url(r'^buscar_producto_por_empresa$', login_required(FilterView.as_view(filterset_class=ProductoFilter,template_name='stock_por_empresa_filtro_list.html')), name='buscar_producto_por_empresa'),

   	

]	

base_sistema/base_sistema/urls.py
# from django.conf.urls import url,include
# from django.contrib import admin
# from django.contrib.auth.views import login

# # from django.contrib.auth import views as auth_views
# # from django.views.generic.base import TemplateView


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from base_sistema.views import pedidoPDF,empresasPDF,perfilPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),#importando las urls del 
    #admin que trae django por defecto
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logout.html'}, name='logout'),
    url(r'^productos/', include('app.productos.urls', namespace="productos")),#name_space
    #son los nombres de las urls globalesy 'app.productos.urls' es la ruta del archivo  
    url(r'^perfil/', include('app.perfil.urls',namespace="perfil")),
    ## REPORTES GENERALES
    url(r'^pedido_pdf/',pedidoPDF.as_view(), name='pedido_pdf'),
    url(r'^empresas_pdf/',empresasPDF.as_view(), name='empresas_pdf'),
    url(r'^perfiles_pdf/',perfilPDF.as_view(), name='perfiles_pdf'),


]

base_sistema/templates/base/base.html
{%extends  'base/base_menu.html'%}
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block extrahead %}
	    
	{% endblock extrahead %}
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}" >
	<link rel="stylesheet" href="{% static 'css/navbar_login.css' %}">  
 

	
		

</head>

  <body>
  {% block header %}
   {% endblock header %}
   {% block nav_bar %}
   <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href="{% url 'home' %}"><strong> Sistema de Inventarios</strong></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarColor01">

		  <ul class="navbar-nav mr-auto">

			<li class="nav-item ">
			  <a class="nav-link" href="#"> <strong>Registrate</strong><span class="sr-only">(current)</span></a>
			</li>
			
			<li class="nav-item" >
				<a class="nav-link" href="#"><strong>Recuperar clave usuario</strong></a>
			</li>
		</div>
	  </nav>
      <br>
 <br>
 <br>
 {% endblock nav_bar%}

  

{% block content %}
    
{% endblock content %}


  	
  </body>
  {% block footer %} 
  {% endblock footer%}
  </html>
 

base_sistema/templates/base/base_menu.html
<!--  -->


  {% load staticfiles %}
    <!DOCTYPE html>
    <html >
		{% block head %}
    	<head>
    		<meta charset="utf-8">
				<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
				<link rel="stylesheet" href="{% static 'css/base_menu.css' %}">
				<link rel="stylesheet" href="{% static 'fondo_forms.css' %}">
				<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
				<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
				<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
				<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
				<title>

        {% block title %}Inventario de mercaderia{% endblock %}
		
			</title>
			 </head>
			 <body>
			{% endblock %}	
			{% block header %}

			{% endblock header %}

			{% block nav_bar %} 
		
	  <nav  class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
		<a class="navbar-brand" href="{% url 'home' %}"><strong> Sistema de Inventarios</strong></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarColor01">

		  <ul class="navbar-nav mr-auto">

			<li class="nav-item ">
			  <a class="nav-link" href="{% url 'perfil:empresas_index' %}"> <strong>Empresas</strong><span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'productos:index_productos' %}"><strong>Mercaderia</strong></a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'productos:inventario_view' %}"><strong>Control de Inventarios</strong></a>
			</li>
			<li class="nav-item" >
				<a class="nav-link" href="{% url 'perfil:index' %}"><strong>Usuarios</strong></a>
			</li>

			<li class="nav-item">
			  <a class="nav-link" href="{% url 'logout' %}"><strong>Salir</strong></a>
			</li>
		  </ul>
		  <form class="form-inline my-2 my-lg-0">
			<input class="botones form-control mr-sm-2" type="search" name="busqueda" placeholder="Buscar por palabra"  required>
			<button class="botones btn btn-secondary my-2 my-sm-0" type="submit" >BUSCAR</button>
		  </form>
		</div>
		</nav>
		<br>
		<br>
		<br>
		<br>
		{% if messages %}
		{% for message in messages %}
		<div id="msg" class="alert alert-info ">
				{{message}}
			<br>
			{% endfor %}
		</div>
		
		{% endif %}	  
		<script>
		setTimeout (function () {
            document.querySelector('#msg').remove();
        },3000);

		</script>
		 <div class="container row">	<!--TODO EL SIDE BAR Y EL CONTENIDO IRAN DENTRO DE UN DIV DEL ARCHIVO BASE -->
				<div class="row">
						
		{% endblock nav_bar%}

		{% block side_bar %}
		
		{% endblock side_bar %}
		
		{% block content %}
	
		 {% endblock content %} 
		 </div>

		</div>
		<br>
		<br>
		<br>
	

		{% block footer %} 
	<div id="footer" class="container-fluid fixed-bottom">
		<nav id="navbar-example2" class="navbar navbar-light bg-light">
				<a class="navbar-brand" href="#"><strong><h5> Creado por: Julio Dominguez</h5></strong></a>
				<ul class="nav nav-pills">
					<li class="nav-item">
						<a class="nav-link" href="#fat">@jdomcanal</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#mdo">Jdomcanal</a>
					</li>
					
			</div>
			{% endblock footer %}

			

	</body>
	
	
	
		
	</html>